analytics: {}
color:
  brandColors:
    - '#B8C0B0'
    - '#107060'
    - '#70A0A0'
    - '#C89030'
    - '#E0C068'
  brandStrength: 1
  lightness: 0.212368
  rhythmicContrast: 0.057386
  saturation: 0.5
cta: {}
layout_spectrum: 0.796875
name: _mowens
opengraph: {}
purpose: []
typography_spectrum: 0.590461
