name: _mowens
favicon: null
layout_spectrum: 0.38465
typography_spectrum: 0.14298
title: Thinking about thoughts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#b4d3f0'
    - '#74abe4'
    - '#772103'
    - '#cd601f'
  brandStrength: 0
  lightness: 0.21236851206049323
  saturation: 0.5
  rhythmicContrast: 0.057386050932109356
purpose: []
